import {
  BadRequestException,
  Injectable,
  Logger,
  NotFoundException,
} from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { createHash, randomBytes, timingSafeEqual } from 'crypto';
import { ChannelType, SpanType } from '@prisma/client';
import { ServerEvents } from '@semaphore-chat/shared';
import { DatabaseService } from '@/database/database.service';
import { MessagesService } from '@/messages/messages.service';
import { LinkPreviewsService } from '@/link-previews/link-previews.service';
import { WebsocketService } from '@/websocket/websocket.service';
import { CreateMessageDto } from '@/messages/dto/create-message.dto';
import { CreateWebhookDto } from './dto/create-webhook.dto';
import {
  CreateWebhookResponseDto,
  WebhookDto,
} from './dto/webhook-response.dto';

/** Raw tokens are 32 random bytes, hex-encoded (64 chars). */
const TOKEN_BYTES = 32;

@Injectable()
export class WebhooksService {
  private readonly logger = new Logger(WebhooksService.name);

  constructor(
    private readonly databaseService: DatabaseService,
    private readonly messagesService: MessagesService,
    private readonly linkPreviewsService: LinkPreviewsService,
    private readonly websocketService: WebsocketService,
    private readonly configService: ConfigService,
  ) {}

  /**
   * Create a new incoming webhook for a TEXT channel. The raw token is
   * returned exactly once, embedded in the execution URL — only its SHA-256
   * hash is persisted.
   */
  async create(
    channelId: string,
    dto: CreateWebhookDto,
    createdBy?: string,
  ): Promise<CreateWebhookResponseDto> {
    const channel = await this.databaseService.channel.findUnique({
      where: { id: channelId },
    });

    if (!channel) {
      throw new NotFoundException('Channel not found');
    }

    if (channel.type !== ChannelType.TEXT) {
      throw new BadRequestException(
        'Webhooks can only be created for text channels',
      );
    }

    const rawToken = randomBytes(TOKEN_BYTES).toString('hex');
    const tokenHash = this.hashToken(rawToken);

    const webhook = await this.databaseService.webhook.create({
      data: {
        channelId,
        name: dto.name,
        avatarUrl: dto.avatarUrl ?? null,
        tokenHash,
        createdBy: createdBy ?? null,
      },
    });

    return {
      id: webhook.id,
      name: webhook.name,
      avatarUrl: webhook.avatarUrl,
      channelId: webhook.channelId,
      createdAt: webhook.createdAt,
      url: this.buildExecutionUrl(webhook.id, rawToken),
    };
  }

  /** List webhooks for a channel — never includes tokens or creator info. */
  async listForChannel(channelId: string): Promise<WebhookDto[]> {
    const webhooks = await this.databaseService.webhook.findMany({
      where: { channelId },
      orderBy: { createdAt: 'asc' },
    });

    return webhooks.map((webhook) => ({
      id: webhook.id,
      name: webhook.name,
      avatarUrl: webhook.avatarUrl,
      channelId: webhook.channelId,
      createdAt: webhook.createdAt,
    }));
  }

  /** Delete a webhook, verifying it belongs to the given channel first. */
  async remove(channelId: string, webhookId: string): Promise<void> {
    const webhook = await this.databaseService.webhook.findUnique({
      where: { id: webhookId },
    });

    if (!webhook || webhook.channelId !== channelId) {
      throw new NotFoundException('Webhook not found');
    }

    await this.databaseService.webhook.delete({ where: { id: webhookId } });
  }

  /**
   * Post a plain-text message on behalf of a webhook. Mirrors
   * MessagesGateway.handleMessage's create -> link previews -> broadcast
   * flow, minus the user-specific steps (slowmode, read receipts,
   * notifications) which don't apply to the webhook path.
   *
   * Returns 404 for both an unknown webhook id and a bad token — the two
   * cases must be indistinguishable to the caller.
   */
  async execute(id: string, token: string, content: string) {
    const webhook = await this.databaseService.webhook.findUnique({
      where: { id },
    });

    if (!webhook || !this.verifyToken(token, webhook.tokenHash)) {
      throw new NotFoundException('Webhook not found');
    }

    const messagePayload: Omit<CreateMessageDto, 'authorId'> & {
      authorId: null;
      webhookId: string;
    } = {
      id: '', // generated by Prisma
      channelId: webhook.channelId,
      directMessageGroupId: null,
      authorId: null,
      sentAt: new Date(),
      editedAt: null,
      deletedAt: null,
      spans: [
        {
          type: SpanType.PLAINTEXT,
          text: content,
          userId: null,
          specialKind: null,
          communityId: null,
          aliasId: null,
          emojiId: null,
        },
      ],
      attachments: [],
      pendingAttachments: 0,
      searchText: null,
      pinned: false,
      pinnedAt: null,
      pinnedBy: null,
      deletedBy: null,
      deletedByReason: null,
      parentMessageId: null,
      replyCount: 0,
      lastReplyAt: null,
      webhookId: webhook.id,
    };

    const message = await this.messagesService.create(messagePayload);

    // Process link previews (async, non-blocking) — same as the gateway.
    this.linkPreviewsService
      .processMessageLinkPreviews(
        message.id,
        message.spans,
        webhook.channelId,
        ServerEvents.UPDATE_MESSAGE,
      )
      .catch((error) =>
        this.logger.error(
          'Failed to process link previews for webhook message',
          error,
        ),
      );

    // Enrich message with file metadata before emitting (consistent shape).
    const enrichedMessage =
      this.messagesService.enrichMessageWithFileMetadata(message);

    this.websocketService.sendToRoom(
      webhook.channelId,
      ServerEvents.NEW_MESSAGE,
      { message: enrichedMessage },
    );

    return { id: message.id };
  }

  private hashToken(token: string): string {
    return createHash('sha256').update(token).digest('hex');
  }

  /** Timing-safe comparison of the presented token's hash against the stored hash. */
  private verifyToken(token: string, storedHash: string): boolean {
    const presentedHash = this.hashToken(token);
    const presentedBuffer = Buffer.from(presentedHash, 'hex');
    const storedBuffer = Buffer.from(storedHash, 'hex');

    if (presentedBuffer.length !== storedBuffer.length) {
      return false;
    }

    return timingSafeEqual(presentedBuffer, storedBuffer);
  }

  /**
   * Builds the execution URL returned once at creation time. Uses
   * PUBLIC_APP_URL (absolute) when configured, otherwise falls back to the
   * relative API path.
   */
  private buildExecutionUrl(id: string, rawToken: string): string {
    const path = `/api/webhooks/${id}/${rawToken}`;
    const baseUrl = this.configService.get<string>('PUBLIC_APP_URL');
    if (!baseUrl) {
      return path;
    }
    return `${baseUrl.replace(/\/+$/, '')}${path}`;
  }
}
