import { Injectable, Logger } from '@nestjs/common';
import { OnEvent } from '@nestjs/event-emitter';
import { ServerEvents } from '@semaphore-chat/shared';
import { WebsocketService } from '@/websocket/websocket.service';
import { RoomName } from '@/common/utils/room-name.util';
import {
  CLIP_MESSAGE_CREATE,
  ClipMessageCreateEvent,
  ClipMessageCreateResult,
} from '@/common/events/clip-message.events';
import { MessagesService } from './messages.service';
import { CreateMessageDto } from './dto/create-message.dto';

/**
 * Creates and broadcasts replay-clip messages on behalf of the LiveKit module.
 *
 * The LiveKit module emits CLIP_MESSAGE_CREATE via `EventEmitter2.emitAsync`
 * instead of importing MessagesService directly, which would re-introduce the
 * MessagesModule -> RoomsModule -> VoicePresenceModule -> LivekitModule ->
 * MessagesModule circular dependency.
 */
@Injectable()
export class ClipMessageListener {
  private readonly logger = new Logger(ClipMessageListener.name);

  constructor(
    private readonly messagesService: MessagesService,
    private readonly websocketService: WebsocketService,
  ) {}

  // suppressErrors: false — @OnEvent swallows handler exceptions by default,
  // which would resolve the emitter's emitAsync to [undefined] and turn a
  // create failure into an opaque TypeError. With this, the original
  // exception propagates to the emitting HTTP handler.
  @OnEvent(CLIP_MESSAGE_CREATE, { suppressErrors: false })
  async handleClipMessageCreate(
    event: ClipMessageCreateEvent,
  ): Promise<ClipMessageCreateResult> {
    const messagePayload: CreateMessageDto = {
      id: '', // Will be generated by Prisma
      channelId:
        event.destination === 'channel' && event.targetChannelId
          ? event.targetChannelId
          : null,
      directMessageGroupId:
        event.destination === 'dm' && event.targetDirectMessageGroupId
          ? event.targetDirectMessageGroupId
          : null,
      authorId: event.authorId,
      sentAt: new Date(),
      editedAt: null,
      deletedAt: null,
      spans: [
        {
          type: 'PLAINTEXT',
          text: `Replay clip - ${event.durationSeconds}s (${event.sizeMB}MB)`,
          userId: null,
          specialKind: null,
          communityId: null,
          aliasId: null,
        },
      ],
      attachments: [event.fileId],
      pendingAttachments: 0,
      searchText: null,
      pinned: false,
      pinnedAt: null,
      pinnedBy: null,
      deletedBy: null,
      deletedByReason: null,
      parentMessageId: null,
      replyCount: 0,
      lastReplyAt: null,
    };

    this.logger.log(
      `Creating clip message with file attachment: ${event.fileId}`,
    );
    const message = await this.messagesService.create(messagePayload);

    // Enrich with file metadata for WebSocket clients
    const enrichedMessage =
      this.messagesService.enrichMessageWithFileMetadata(message);

    // Emit WebSocket event to notify channel/DM members
    if (event.destination === 'channel' && event.targetChannelId) {
      this.websocketService.sendToRoom(
        event.targetChannelId,
        ServerEvents.NEW_MESSAGE,
        { message: enrichedMessage },
      );
    } else if (event.destination === 'dm' && event.targetDirectMessageGroupId) {
      this.websocketService.sendToRoom(
        RoomName.dmGroup(event.targetDirectMessageGroupId),
        ServerEvents.NEW_DM,
        { message: enrichedMessage },
      );
    }

    this.logger.log(
      `Posted clip message ${message.id} to ${event.destination}`,
    );

    return { messageId: message.id };
  }
}
