// src/websocket/server-events.enum.ts (frontend copy)
export enum ServerEvents {
  NEW_MESSAGE = "newMessage",
  UPDATE_MESSAGE = "updateMessage",
  DELETE_MESSAGE = "deleteMessage",
  REACTION_ADDED = "reactionAdded",
  REACTION_REMOVED = "reactionRemoved",
  READ_RECEIPT_UPDATED = "readReceiptUpdated",
  NEW_DM = "newDirectMessage",
  NEW_MENTION = "newMention",
  NOTIFICATION = "notification",
  USER_ONLINE = "userOnline",
  USER_OFFLINE = "userOffline",
  USER_TYPING = "userTyping",
  VOICE_CHANNEL_USER_JOINED = "voiceChannelUserJoined",
  VOICE_CHANNEL_USER_LEFT = "voiceChannelUserLeft",
  VOICE_CHANNEL_USER_UPDATED = "voiceChannelUserUpdated",
  ACK = "ack",
  ERROR = "error",
}
