// src/websocket/server-events.enum.ts (frontend copy)
export enum ServerEvents {
  NEW_MESSAGE = "newMessage",
  UPDATE_MESSAGE = "updateMessage",
  DELETE_MESSAGE = "deleteMessage",
  REACTION_ADDED = "reactionAdded",
  REACTION_REMOVED = "reactionRemoved",
  READ_RECEIPT_UPDATED = "readReceiptUpdated",
  NEW_DM = "newDirectMessage",
  NEW_NOTIFICATION = "newNotification",
  NOTIFICATION_READ = "notificationRead",
  USER_ONLINE = "userOnline",
  USER_OFFLINE = "userOffline",
  USER_TYPING = "userTyping",
  VOICE_CHANNEL_USER_JOINED = "voiceChannelUserJoined",
  VOICE_CHANNEL_USER_LEFT = "voiceChannelUserLeft",
  VOICE_CHANNEL_USER_UPDATED = "voiceChannelUserUpdated",
  REPLAY_BUFFER_STOPPED = "replayBufferStopped",
  REPLAY_BUFFER_FAILED = "replayBufferFailed",
  ACK = "ack",
  ERROR = "error",
}
