// RBAC Actions mapping - keep in sync with backend RbacActions enum
export const RBAC_ACTIONS = {
  // Message Management
  CREATE_MESSAGE: 'CREATE_MESSAGE',
  UPDATE_MESSAGE: 'UPDATE_MESSAGE',
  DELETE_MESSAGE: 'DELETE_MESSAGE', 
  READ_MESSAGE: 'READ_MESSAGE',

  // Channel Management
  CREATE_CHANNEL: 'CREATE_CHANNEL',
  UPDATE_CHANNEL: 'UPDATE_CHANNEL',
  DELETE_CHANNEL: 'DELETE_CHANNEL',
  READ_CHANNEL: 'READ_CHANNEL',
  JOIN_CHANNEL: 'JOIN_CHANNEL',

  // Community Management
  CREATE_COMMUNITY: 'CREATE_COMMUNITY',
  UPDATE_COMMUNITY: 'UPDATE_COMMUNITY',
  DELETE_COMMUNITY: 'DELETE_COMMUNITY',
  READ_COMMUNITY: 'READ_COMMUNITY',
  READ_ALL_COMMUNITIES: 'READ_ALL_COMMUNITIES',

  // Member Management
  CREATE_MEMBER: 'CREATE_MEMBER',
  UPDATE_MEMBER: 'UPDATE_MEMBER',
  DELETE_MEMBER: 'DELETE_MEMBER',
  READ_MEMBER: 'READ_MEMBER',

  // Role Management
  CREATE_ROLE: 'CREATE_ROLE',
  UPDATE_ROLE: 'UPDATE_ROLE',
  DELETE_ROLE: 'DELETE_ROLE',
  READ_ROLE: 'READ_ROLE',

  // User Management
  CREATE_USER: 'CREATE_USER',
  DELETE_USER: 'DELETE_USER',
  READ_USER: 'READ_USER',
  UPDATE_USER: 'UPDATE_USER',

  // Invite Management
  CREATE_INVITE: 'CREATE_INVITE',
  DELETE_INVITE: 'DELETE_INVITE',
  CREATE_INSTANCE_INVITE: 'CREATE_INSTANCE_INVITE',
  DELETE_INSTANCE_INVITE: 'DELETE_INSTANCE_INVITE',
  READ_INSTANCE_INVITE: 'READ_INSTANCE_INVITE',
  UPDATE_INSTANCE_INVITE: 'UPDATE_INSTANCE_INVITE',

  // Alias/Mention Groups
  CREATE_ALIAS_GROUP: 'CREATE_ALIAS_GROUP',
  UPDATE_ALIAS_GROUP: 'UPDATE_ALIAS_GROUP',
  DELETE_ALIAS_GROUP: 'DELETE_ALIAS_GROUP',
  READ_ALIAS_GROUP: 'READ_ALIAS_GROUP',
  CREATE_ALIAS_GROUP_MEMBER: 'CREATE_ALIAS_GROUP_MEMBER',
  DELETE_ALIAS_GROUP_MEMBER: 'DELETE_ALIAS_GROUP_MEMBER',
  READ_ALIAS_GROUP_MEMBER: 'READ_ALIAS_GROUP_MEMBER',
  UPDATE_ALIAS_GROUP_MEMBER: 'UPDATE_ALIAS_GROUP_MEMBER',

  // Reactions & Attachments
  CREATE_REACTION: 'CREATE_REACTION',
  DELETE_REACTION: 'DELETE_REACTION',
  CREATE_ATTACHMENT: 'CREATE_ATTACHMENT',
  DELETE_ATTACHMENT: 'DELETE_ATTACHMENT',

  // Moderation
  BAN_USER: 'BAN_USER',
  KICK_USER: 'KICK_USER',
  TIMEOUT_USER: 'TIMEOUT_USER',
  UNBAN_USER: 'UNBAN_USER',
  PIN_MESSAGE: 'PIN_MESSAGE',
  UNPIN_MESSAGE: 'UNPIN_MESSAGE',
  DELETE_ANY_MESSAGE: 'DELETE_ANY_MESSAGE',
  VIEW_BAN_LIST: 'VIEW_BAN_LIST',
  VIEW_MODERATION_LOGS: 'VIEW_MODERATION_LOGS',
} as const;

export type RbacAction = typeof RBAC_ACTIONS[keyof typeof RBAC_ACTIONS];

// Grouped permissions for better UI display
export const PERMISSION_GROUPS = {
  'Messages': [
    RBAC_ACTIONS.CREATE_MESSAGE,
    RBAC_ACTIONS.UPDATE_MESSAGE,
    RBAC_ACTIONS.DELETE_MESSAGE,
    RBAC_ACTIONS.READ_MESSAGE,
  ],
  'Channels': [
    RBAC_ACTIONS.CREATE_CHANNEL,
    RBAC_ACTIONS.UPDATE_CHANNEL,
    RBAC_ACTIONS.DELETE_CHANNEL,
    RBAC_ACTIONS.READ_CHANNEL,
    RBAC_ACTIONS.JOIN_CHANNEL,
  ],
  'Community': [
    RBAC_ACTIONS.UPDATE_COMMUNITY,
    RBAC_ACTIONS.DELETE_COMMUNITY,
    RBAC_ACTIONS.READ_COMMUNITY,
    RBAC_ACTIONS.READ_ALL_COMMUNITIES,
  ],
  'Members': [
    RBAC_ACTIONS.CREATE_MEMBER,
    RBAC_ACTIONS.UPDATE_MEMBER,
    RBAC_ACTIONS.DELETE_MEMBER,
    RBAC_ACTIONS.READ_MEMBER,
  ],
  'Roles': [
    RBAC_ACTIONS.CREATE_ROLE,
    RBAC_ACTIONS.UPDATE_ROLE,
    RBAC_ACTIONS.DELETE_ROLE,
    RBAC_ACTIONS.READ_ROLE,
  ],
  'Users': [
    RBAC_ACTIONS.CREATE_USER,
    RBAC_ACTIONS.UPDATE_USER,
    RBAC_ACTIONS.DELETE_USER,
    RBAC_ACTIONS.READ_USER,
  ],
  'Invites': [
    RBAC_ACTIONS.CREATE_INVITE,
    RBAC_ACTIONS.DELETE_INVITE,
    RBAC_ACTIONS.CREATE_INSTANCE_INVITE,
    RBAC_ACTIONS.DELETE_INSTANCE_INVITE,
    RBAC_ACTIONS.READ_INSTANCE_INVITE,
    RBAC_ACTIONS.UPDATE_INSTANCE_INVITE,
  ],
  'Content': [
    RBAC_ACTIONS.CREATE_REACTION,
    RBAC_ACTIONS.DELETE_REACTION,
    RBAC_ACTIONS.CREATE_ATTACHMENT,
    RBAC_ACTIONS.DELETE_ATTACHMENT,
  ],
  'Alias Groups': [
    RBAC_ACTIONS.CREATE_ALIAS_GROUP,
    RBAC_ACTIONS.UPDATE_ALIAS_GROUP,
    RBAC_ACTIONS.DELETE_ALIAS_GROUP,
    RBAC_ACTIONS.READ_ALIAS_GROUP,
    RBAC_ACTIONS.CREATE_ALIAS_GROUP_MEMBER,
    RBAC_ACTIONS.DELETE_ALIAS_GROUP_MEMBER,
    RBAC_ACTIONS.READ_ALIAS_GROUP_MEMBER,
    RBAC_ACTIONS.UPDATE_ALIAS_GROUP_MEMBER,
  ],
  'Moderation': [
    RBAC_ACTIONS.BAN_USER,
    RBAC_ACTIONS.UNBAN_USER,
    RBAC_ACTIONS.KICK_USER,
    RBAC_ACTIONS.TIMEOUT_USER,
    RBAC_ACTIONS.PIN_MESSAGE,
    RBAC_ACTIONS.UNPIN_MESSAGE,
    RBAC_ACTIONS.DELETE_ANY_MESSAGE,
    RBAC_ACTIONS.VIEW_BAN_LIST,
    RBAC_ACTIONS.VIEW_MODERATION_LOGS,
  ],
};

// Human readable action names
export const ACTION_LABELS: Record<RbacAction, string> = {
  // Messages
  [RBAC_ACTIONS.CREATE_MESSAGE]: 'Send messages',
  [RBAC_ACTIONS.UPDATE_MESSAGE]: 'Edit messages',
  [RBAC_ACTIONS.DELETE_MESSAGE]: 'Delete messages',
  [RBAC_ACTIONS.READ_MESSAGE]: 'Read messages',

  // Channels
  [RBAC_ACTIONS.CREATE_CHANNEL]: 'Create channels',
  [RBAC_ACTIONS.UPDATE_CHANNEL]: 'Edit channels',
  [RBAC_ACTIONS.DELETE_CHANNEL]: 'Delete channels',
  [RBAC_ACTIONS.READ_CHANNEL]: 'View channels',
  [RBAC_ACTIONS.JOIN_CHANNEL]: 'Join channels',

  // Community
  [RBAC_ACTIONS.UPDATE_COMMUNITY]: 'Edit community',
  [RBAC_ACTIONS.DELETE_COMMUNITY]: 'Delete community',
  [RBAC_ACTIONS.READ_COMMUNITY]: 'View community',
  [RBAC_ACTIONS.READ_ALL_COMMUNITIES]: 'View all communities',

  // Members
  [RBAC_ACTIONS.CREATE_MEMBER]: 'Add members',
  [RBAC_ACTIONS.UPDATE_MEMBER]: 'Edit members',
  [RBAC_ACTIONS.DELETE_MEMBER]: 'Remove members',
  [RBAC_ACTIONS.READ_MEMBER]: 'View members',

  // Roles
  [RBAC_ACTIONS.CREATE_ROLE]: 'Create roles',
  [RBAC_ACTIONS.UPDATE_ROLE]: 'Edit roles',
  [RBAC_ACTIONS.DELETE_ROLE]: 'Delete roles',
  [RBAC_ACTIONS.READ_ROLE]: 'View roles',

  // Users
  [RBAC_ACTIONS.CREATE_USER]: 'Create users',
  [RBAC_ACTIONS.UPDATE_USER]: 'Edit users',
  [RBAC_ACTIONS.DELETE_USER]: 'Delete users',
  [RBAC_ACTIONS.READ_USER]: 'View users',

  // Invites
  [RBAC_ACTIONS.CREATE_INVITE]: 'Create invites',
  [RBAC_ACTIONS.DELETE_INVITE]: 'Delete invites',
  [RBAC_ACTIONS.CREATE_INSTANCE_INVITE]: 'Create instance invites',
  [RBAC_ACTIONS.DELETE_INSTANCE_INVITE]: 'Delete instance invites',
  [RBAC_ACTIONS.READ_INSTANCE_INVITE]: 'View invites',
  [RBAC_ACTIONS.UPDATE_INSTANCE_INVITE]: 'Update invites',

  // Content
  [RBAC_ACTIONS.CREATE_REACTION]: 'Add reactions',
  [RBAC_ACTIONS.DELETE_REACTION]: 'Remove reactions',
  [RBAC_ACTIONS.CREATE_ATTACHMENT]: 'Upload files',
  [RBAC_ACTIONS.DELETE_ATTACHMENT]: 'Delete files',

  // Alias Groups
  [RBAC_ACTIONS.CREATE_ALIAS_GROUP]: 'Create mention groups',
  [RBAC_ACTIONS.UPDATE_ALIAS_GROUP]: 'Edit mention groups',
  [RBAC_ACTIONS.DELETE_ALIAS_GROUP]: 'Delete mention groups',
  [RBAC_ACTIONS.READ_ALIAS_GROUP]: 'View mention groups',
  [RBAC_ACTIONS.CREATE_ALIAS_GROUP_MEMBER]: 'Add to mention groups',
  [RBAC_ACTIONS.DELETE_ALIAS_GROUP_MEMBER]: 'Remove from mention groups',
  [RBAC_ACTIONS.READ_ALIAS_GROUP_MEMBER]: 'View mention group members',
  [RBAC_ACTIONS.UPDATE_ALIAS_GROUP_MEMBER]: 'Edit mention group members',

  // Moderation
  [RBAC_ACTIONS.BAN_USER]: 'Ban users',
  [RBAC_ACTIONS.UNBAN_USER]: 'Unban users',
  [RBAC_ACTIONS.KICK_USER]: 'Kick users',
  [RBAC_ACTIONS.TIMEOUT_USER]: 'Timeout users',
  [RBAC_ACTIONS.PIN_MESSAGE]: 'Pin messages',
  [RBAC_ACTIONS.UNPIN_MESSAGE]: 'Unpin messages',
  [RBAC_ACTIONS.DELETE_ANY_MESSAGE]: 'Delete any message',
  [RBAC_ACTIONS.VIEW_BAN_LIST]: 'View ban list',
  [RBAC_ACTIONS.VIEW_MODERATION_LOGS]: 'View moderation logs',
};