###
# @name login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

###
# @name refresh
POST http://localhost:3000/api/auth/refresh

###

@jwt = {{login.response.body.accessToken}}
@jwt = {{refresh.response.body.accessToken}}


###
# @name createCommunity
POST http://localhost:3000/api/community
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "name": "{{$guid}} Community",
    "description": "Another new community"
}

###
GET http://localhost:3000/api/community/mine
Authorization: Bearer {{jwt}}

###
# 404 check
GET http://localhost:3000/api/community/6813d70aaaaaa2b9c24d5217
Authorization: Bearer {{jwt}}

###
@communityId = {{createCommunity.response.body.id}}

###

GET http://localhost:3000/api/community/{{communityId}}
Authorization: Bearer {{jwt}}

###

###
# Update
PATCH http://localhost:3000/api/community/{{communityId}}
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
    "name": "Updated Community Name",
    "description": "Updated community description"
}

###
# Delete
DELETE http://localhost:3000/api/community/{{communityId}}
Authorization: Bearer {{jwt}}

###

# Delete
DELETE http://localhost:3000/api/community/6813e26934655b3da65eb8ed
Authorization: Bearer {{jwt}}

###

###

GET http://localhost:3000/api/community/{{communityId}}
Authorization: Bearer {{jwt}}

###