###
# @name login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

###

###
# @name login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "normaluser",
  "password": "regularpw456"
}

###

@jwt = {{login.response.body.accessToken}}

###
# @name invite
POST http://localhost:3000/api/invite
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "maxUses": 5,
    "communityIds": []
}
###

@code = {{invite.response.body.code}}

### Register another user (normal)
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "username": "user-{{$guid}}",
  "password": "regularpw456",
  "email": "user-{{$guid}}@example.com",
  "code": "{{code}}"
}

###