### Register a new user
POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "adminuser",
  "password": "supersecurepw123",
  "email": "admin@example.com"
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "adminuser",
  "password": "supersecurepw123"
}

###

POST http://localhost:3000/auth/logout
Content-Type: application/json

###

### Register another user (normal)
POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "normaluser",
  "password": "regularpw456",
  "email": "user@example.com"
}

###

### Get user by username (not implemented, but plan for it!)
GET http://localhost:3000/users/username/adminuser

###

### Get user by id (replace with actual ID returned above)
GET http://localhost:3000/users/680ff0d909e7b7793e603230

###